server:
  port: 80


#######datasource配置#######
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  #######freemarker配置#######
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false

#######mybatis配置#######
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.wbp.boot.entity

